telerik/blazor-ui

TelerikBlazor/TelerikBlazor.App/Pages/Grid/FormEdit.cshtml
TelerikBlazor/TelerikBlazor.App/Shared/NavMenu.cshtml

Added a Form Edit example for the Grid.
Made nav menu dynamic for the grid examples.

Added a Form Edit example for the Grid.

---

TelerikBlazor/TelerikBlazor.App/Pages/Grid/Columns.cshtml
TelerikBlazor/TelerikBlazor.App/Pages/Grid/DataBind.cshtml
TelerikBlazor/TelerikBlazor.App/Pages/Grid/Editing.cshtml
TelerikBlazor/TelerikBlazor.App/Pages/Grid/FormEdit.cshtml
TelerikBlazor/TelerikBlazor.App/Pages/Grid/Index.cshtml
TelerikBlazor/TelerikBlazor.App/Pages/Grid/Paging.cshtml
TelerikBlazor/TelerikBlazor.App/Pages/Grid/Sorting.cshtml
TelerikBlazor/TelerikBlazor.App/Pages/Grid/Templates.cshtml
TelerikBlazor/TelerikBlazor.App/Pages/_ViewImports.cshtml

- Removed usage of AsQueryable, this is not an awaitable function; Used ToListAsync instead.
- Added Title attributes where needed
- Used self closing tags where available
- Removed unused using statements

Refactored all Grid pages

---

TelerikBlazor.Client/Pages/Grid/Editing_InCell.cshtml
TelerikBlazor.Client/Pages/NumericTextbox/Index.cshtml
TelerikBlazor.Client/Pages/Window/Modal.cshtml
TelerikBlazor.Client/Shared/NavMenu.cshtml

I updated a few small bits on the examples.
- Fixed  an encoding error or typo on a less than symbol `<`
- Added a modal dialog example
- Replaced icons in the NavMenu with Kendo Icons

Refactor Examples

---

sample-applications/blazor-stocks/Client/BlazorFinancePortfolio.Client.csproj
sample-applications/blazor-stocks/Server/BlazorFinancePortfolio.Server.csproj

Related to https://github.com/telerik/blazor/issues/1326

chore: update to wasm 3.2.1

---

sample-applications/blazor-dashboard/BlazorDashboard/BlazorDashboard.csproj
sample-applications/blazor-dashboard/README.md
sample-applications/blazor-stocks/Client/BlazorFinancePortfolio.Client.csproj
sample-applications/blazor-stocks/Client/Program.cs
sample-applications/blazor-stocks/Server/BlazorFinancePortfolio.Server.csproj
sample-applications/blazor-stocks/Shared/BlazorFinancePortfolio.Shared.csproj
sample-applications/blazor-stocks/readme.md

This PR updates the Dashboard and Stocks apps to net5.0
Related to: https://github.com/telerik/blazor/issues/1765

Update sample apps to net5.0

---

common/message-box/callback-event/Pages/FetchData.razor
common/message-box/dynamic-creation/Pages/FetchData.razor
common/message-box/dynamic-creation/Shared/PopupLayout.razor
common/pdf-jpg-export-js/PdfExportJS/Pages/Export_Chart.razor
common/pdf-jpg-export-js/PdfExportJS/Pages/Index.razor
drawer/sidenav/Shared/MainLayout.razor
drawer/template/template/Shared/MainLayout.razor
drawer/two-drawers/TwoDrawers/Shared/MainLayout.razor
editor/ImportExport/EditorImportExport/Pages/Index.razor
grid/batch-editing/BatchEditing.csproj
grid/batch-editing/Pages/Index.razor
grid/custom-popup-form/custom_popup_form.csproj
grid/datasourcerequest-on-server/CustomSerializer/Client/CustomSerializer.Client.csproj
grid/datasourcerequest-on-server/CustomSerializer/Server/CustomSerializer.Server.csproj
grid/datasourcerequest-on-server/CustomSerializer/Shared/CustomSerializer.Shared.csproj
grid/datasourcerequest-on-server/WasmApp/Client/WasmApp.Client.csproj
grid/datasourcerequest-on-server/WasmApp/Server/WasmApp.Server.csproj
grid/datasourcerequest-on-server/WasmApp/Shared/WasmApp.Shared.csproj
grid/export-to-xlsx-hierarchy/Pages/Index.razor
grid/pdf-export-server/Client/Pages/Index.razor
grid/pdf-export-server/ServerSideSample/Pages/Index.razor
grid/print/Pages/PrintSomeColumns.razor
grid/print/Pages/PrintWholeGrid.razor
grid/remote-validation/Client/Pages/Index.razor
listview/ValidationExamples/ValidationExamples/Pages/AsyncMethods.razor
listview/ValidationExamples/ValidationExamples/Pages/BasicFormValidation.razor
listview/ValidationExamples/ValidationExamples/Pages/CustomForm.razor

things I did not properly find-replace, mostly.

Iconname build errors

---

common/kendo-in-blazor/KendoInBlazor/Pages/Index.razor
common/kendo-in-blazor/KendoInBlazor/Pages/_Host.cshtml
common/kendo-in-blazor/KendoInBlazor/Shared/MyKendoPdfViewer.razor
common/kendo-in-blazor/KendoInBlazor/wwwroot/myJsInteropForjQueryWidgets.js

The customer had a good way of loading the PDFjs resources. I thought that this would be nice to include in the sample's repository for reference.
Also, added additional parameters for width and height for further reference.

add script loading optimization for Kendo PDF Viewer

---

drawer/two-drawers/TwoDrawers/Shared/MainLayout.razor

- In the MainLayout.razor added CSS rule for height
Targets #90

chore(drawer):added height in the two drawers example main layout

---

sample-applications/blazing-coffee/BlazingCoffee/Client/Theme/_drawer.scss
sample-applications/blazing-coffee/BlazingCoffee/Client/Theme/main.scss

chore(blazingCoffee): fix drawer layout height and scrollbar #104

---

common/hybrid-blazor-apps/BlazorWinFormsApp/BlazorWinFormsApp.csproj
common/hybrid-blazor-apps/BlazorWinFormsApp/Form1.designer.cs
common/hybrid-blazor-apps/BlazorWinFormsApp/Form1.resx
common/hybrid-blazor-apps/BlazorWpfApp/BlazorWpfApp.csproj
common/hybrid-blazor-apps/WebviewAppShared/WebviewAppShared.csproj

Related to https://github.com/telerik/blazor/issues/2932

 chore: update hybrid apps to net 6 preview 7

---

common/hybrid-blazor-apps/BlazorWinFormsApp/BlazorWinFormsApp.csproj
common/hybrid-blazor-apps/BlazorWpfApp/BlazorWpfApp.csproj
common/hybrid-blazor-apps/WebviewAppShared/WebviewAppShared.csproj

Related to https://github.com/telerik/blazor/issues/3012

chore: update winforms and wpf hybrid apps to net 6 rc 1

---

common/hybrid-blazor-apps/README.md

Update instructions for hybrid apps.

chore: update readme

---

sample-applications/blazor-stocks/Client/BlazorFinancePortfolio.Client.csproj
sample-applications/blazor-stocks/Server/BlazorFinancePortfolio.Server.csproj
sample-applications/blazor-stocks/Shared/BlazorFinancePortfolio.Shared.csproj

> **IMPORTANT:** Do not merge, pending on the release of .NET 6.0 and update all nuget packages to new 6.0 versions.

chore(blazor-stocks): update to net 6

---

sample-applications/blazing-coffee/BlazingCoffee/Client/BlazingCoffee.Client.csproj
sample-applications/blazing-coffee/BlazingCoffee/Server/BlazingCoffee.Server.csproj
sample-applications/blazing-coffee/BlazingCoffee/Server/Data/ApplicationDbContext.cs
sample-applications/blazing-coffee/BlazingCoffee/Shared/BlazingCoffee.Shared.csproj

> **IMPORTANT:** Do not merge, pending on the release of .NET 6.0 and update all nuget packages to new 6.0 versions.

chore(blazing-coffee): update to net 6

---

sample-applications/blazor-dashboard/BlazorDashboard/BlazorDashboard.csproj

> **IMPORTANT:** Do not merge, pending on the release of .NET 6.0 and update all nuget packages to new 6.0 versions.

chore(blazor-dashboard): update to net 6

---

tooltip/in-grid/Pages/Index.razor
tooltip/in-grid/Pages/TooltipPerCell.razor
tooltip/in-grid/Shared/NavMenu.razor
tooltip/in-grid/TooltipForGridElements.csproj
tooltip/in-grid/readme.md

- Added a new page with an example that shows only one instance of the Tooltip for the whole Grid.

kb(grid,tooltip):tooltip in grid example changes

---

sample-applications/blazing-coffee/BlazingCoffee/Client/Program.cs
sample-applications/blazor-dashboard/BlazorDashboard/Pages/Dashboard.razor
sample-applications/blazor-dashboard/BlazorDashboard/Pages/Profile.razor
sample-applications/blazor-dashboard/BlazorDashboard/Pages/SignIn.razor
sample-applications/blazor-dashboard/BlazorDashboard/Shared/IssuesRenderers/IssueDetails.razor
sample-applications/blazor-dashboard/BlazorDashboard/Shared/MainLayout.razor

targets https://github.com/telerik/blazor/issues/3747 
- UI changes because of 3.0 and incorrect positions
- Localization is not working
Checkbox issue with color seems expected and will not be handled

Sample applications update

---

common/hybrid-blazor-apps/README.md

Add a link to the official MAUI docs. /cc @mariaveledinova

chore(hybrid-apps): update readme

---

sample-applications/blazing-coffee/BlazingCoffee/Client/BlazingCoffee.Client.csproj
sample-applications/blazing-coffee/BlazingCoffee/Server/BlazingCoffee.Server.csproj
sample-applications/blazing-coffee/BlazingCoffee/Shared/BlazingCoffee.Shared.csproj
sample-applications/blazor-dashboard/BlazorDashboard/BlazorDashboard.csproj
sample-applications/blazor-stocks/Client/BlazorFinancePortfolio.Client.csproj
sample-applications/blazor-stocks/Server/BlazorFinancePortfolio.Server.csproj
sample-applications/blazor-stocks/Shared/BlazorFinancePortfolio.Shared.csproj

Related to: https://github.com/telerik/blazor/issues/4851

chore(sample-applications): bump version to net7

---

README.md

To be merged after the release of 4.0.0
TODO prior merging:

chore: update readme with new components

---

README.md

Related to: telerik/blazor#6793

chore: add pivotgrid in the readme file

---

grid/scroll-to-selected-row/readme.md
grid/scroll-to-selected-row/scroll-to-selected-row/wwwroot/scroll-to-row.js

fix(grid): Change scrollIntoView behavior in KB

---

sample-applications/blazing-coffee/BlazingCoffee/Client/Pages/Index.razor
sample-applications/blazing-coffee/BlazingCoffee/Client/Pages/Profile.razor
sample-applications/blazing-coffee/BlazingCoffee/Client/Pages/SalesReports/SalesByDateChart.razor
sample-applications/blazing-coffee/BlazingCoffee/Client/Shared/Layouts/MainLayout.razor
sample-applications/blazing-coffee/BlazingCoffee/Client/Shared/NavMenu/DrawerItem.cs
sample-applications/blazing-coffee/BlazingCoffee/Client/Shared/NavMenu/DrawerNavLink.cs
sample-applications/blazing-coffee/BlazingCoffee/Client/Shared/NavMenu/LoginDisplay.razor
sample-applications/blazing-coffee/BlazingCoffee/Client/Shared/Themes/ThemeChooser.razor
sample-applications/blazing-coffee/BlazingCoffee/Client/_Imports.razor
sample-applications/blazor-dashboard/BlazorDashboard/Pages/SignIn.razor
sample-applications/blazor-dashboard/BlazorDashboard/_Imports.razor
sample-applications/blazor-stocks/Client/Components/StocksGrid/ConfirmButton.razor
sample-applications/blazor-stocks/Client/Pages/Index.razor
sample-applications/blazor-stocks/Client/_Imports.razor

Related to: https://github.com/telerik/blazor/issues/6331

Change font icons to svg icons 

---

sample-applications/blazing-coffee/BlazingCoffee/Server/BlazingCoffee.Server.csproj

Related to: https://github.com/telerik/blazor/issues/7782

chore(sample-apps): update coffee app dpl version

---

sample-applications/blazor-stocks/Server/Startup.cs

Related to: https://github.com/telerik/blazor/issues/7698#issuecomment-1803263739

fix(sample-apps): add stocks app missing middleware

---

sample-applications/blazing-coffee/BlazingCoffee/Client/BlazingCoffee.Client.csproj
sample-applications/blazing-coffee/BlazingCoffee/Client/wwwroot/index.html
sample-applications/blazing-coffee/BlazingCoffee/Server/BlazingCoffee.Server.csproj
sample-applications/blazing-coffee/BlazingCoffee/Server/Startup.cs
sample-applications/blazing-coffee/BlazingCoffee/Shared/BlazingCoffee.Shared.csproj
sample-applications/blazing-coffee/global.json
sample-applications/blazing-coffee/readme.md
sample-applications/blazor-dashboard/BlazorDashboard/App.razor
sample-applications/blazor-dashboard/BlazorDashboard/BlazorDashboard.csproj
sample-applications/blazor-dashboard/BlazorDashboard/Pages/_Host.cshtml
sample-applications/blazor-dashboard/BlazorDashboard/Routes.razor
sample-applications/blazor-dashboard/BlazorDashboard/Startup.cs
sample-applications/blazor-dashboard/README.md
sample-applications/blazor-stocks/Client/BlazorFinancePortfolio.Client.csproj
sample-applications/blazor-stocks/Client/wwwroot/index.html
sample-applications/blazor-stocks/Server/BlazorFinancePortfolio.Server.csproj
sample-applications/blazor-stocks/Server/Startup.cs
sample-applications/blazor-stocks/Shared/BlazorFinancePortfolio.Shared.csproj
sample-applications/blazor-stocks/global.json
sample-applications/blazor-stocks/readme.md

Related to: https://github.com/telerik/blazor/issues/7265#issuecomment-1808563630
https://github.com/telerik/blazor/pull/7918

Revert sample apps changes

---

common/hybrid-blazor-apps/BlazorMauiApp/BlazorMauiApp.csproj
common/hybrid-blazor-apps/BlazorWinFormsApp/BlazorWinFormsApp.csproj
common/hybrid-blazor-apps/BlazorWpfApp/BlazorWpfApp.csproj
common/hybrid-blazor-apps/WebviewAppShared/WebviewAppShared.csproj

Related to: https://github.com/telerik/blazor/issues/7841

chore(hybrid-apps): update packages version

---

README.md

This adds the components introduced in [5.1.0](https://www.telerik.com/support/whats-new/blazor-ui/release-history/ui-for-blazor-5-1-0)

chore: add new components to readme

---

sample-applications/blazing-coffee/BlazingCoffee/Client/Shared/NavMenu/DrawTemplate.razor

Related to: [#9307](https://github.com/telerik/blazor/issues/9307)

fix(Drawer): fix drawer rendering changes

---

sample-applications/blazing-coffee/BlazingCoffee/Server/Startup.cs

Related to: https://github.com/telerik/blazor/issues/9468

chore: blazing coffee disable antiforgery

---

common/grpc-example/datasource-request-result/gRPCsample/Client/Pages/TestGrid.razor
common/grpc-example/datasource-request-result/gRPCsample/Client/Pages/TestGrid.razor.cs
common/grpc-example/datasource-request-result/gRPCsample/Client/Pages/TestGridJSON.razor.cs
common/grpc-example/datasource-request-result/gRPCsample/Client/_Imports.razor
common/grpc-example/datasource-request-result/gRPCsample/Client/gRPCsample.Client.csproj
common/grpc-example/datasource-request-result/gRPCsample/Server/gRPCsample.Server.csproj
common/grpc-example/datasource-request-result/gRPCsample/Shared/Common/DataSourceProtoRequest.cs
common/grpc-example/datasource-request-result/gRPCsample/Shared/gRPCsample.Shared.csproj
grid/datasourcerequest-on-server/CustomSerializer/Client/CustomSerializer.Client.csproj
grid/datasourcerequest-on-server/CustomSerializer/Client/Pages/Index.razor
grid/datasourcerequest-on-server/CustomSerializer/Server/CustomSerializer.Server.csproj
grid/datasourcerequest-on-server/CustomSerializer/Shared/CustomSerializer.Shared.csproj
grid/datasourcerequest-on-server/ServerApp/Pages/Index.razor
grid/datasourcerequest-on-server/ServerApp/Pages/_Host.cshtml
grid/datasourcerequest-on-server/ServerApp/ServerApp.csproj
grid/datasourcerequest-on-server/WasmApp/Client/Pages/Index.razor
grid/datasourcerequest-on-server/WasmApp/Client/WasmApp.Client.csproj
grid/datasourcerequest-on-server/WasmApp/Server/WasmApp.Server.csproj
grid/datasourcerequest-on-server/WasmApp/Shared/WasmApp.Shared.csproj
grid/datasourcerequest-on-server/WebApiFromServerApp/SampleWebApi/SampleWebApi.csproj
grid/datasourcerequest-on-server/WebApiFromServerApp/SampleWebApi/appsettings.json
grid/datasourcerequest-on-server/WebApiFromServerApp/SharedClasses/SharedClasses.csproj
grid/datasourcerequest-on-server/WebApiFromServerApp/WebApiFromServerApp/Pages/GridWithService.razor
grid/datasourcerequest-on-server/WebApiFromServerApp/WebApiFromServerApp/Pages/_Host.cshtml
grid/datasourcerequest-on-server/WebApiFromServerApp/WebApiFromServerApp/WebApiFromServerApp.csproj

closes: https://github.com/telerik/blazor/issues/10708

Remove cast object

---

sample-applications/blazing-coffee/BlazingCoffee/Client/BlazingCoffee.Client.csproj
sample-applications/blazing-coffee/BlazingCoffee/Client/Host.razor
sample-applications/blazing-coffee/BlazingCoffee/Client/wwwroot/js/themeChooser.js
sample-applications/blazing-coffee/BlazingCoffee/Shared/BlazingCoffee.Shared.csproj
sample-applications/blazor-dashboard/BlazorDashboard/App.razor
sample-applications/blazor-dashboard/BlazorDashboard/BlazorDashboard.csproj
sample-applications/blazor-stocks/Client/BlazorFinancePortfolio.Client.csproj
sample-applications/blazor-stocks/Client/Host.razor
sample-applications/blazor-stocks/Shared/BlazorFinancePortfolio.Shared.csproj

This reverts commit fa3a84574ebe3cbe9635cb4136a7630e8836e4d1.

Revert "chore(sample-apps): automatic sync package version"
